name: daniela-diego-wedding
favicon: null
layout_spectrum: 0.9838097374886274
typography_spectrum: 0.11012073373422027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7fc6af'
    - '#ffbc81'
    - '#767676'
    - '#004146'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
